src/Entity/Carousel.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarouselRepository")
 * @Vich\Uploadable
 */
class Carousel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * 
     * @Vich\UploadableField(mapping="carousels", fileNameProperty="imageName")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get the value of imageFile
     *
     * @return  File|null
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @param  File|null  $imageFile
     *
     * @return  self
     */ 
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new DateTime('now');
        }
        return $this;
    }
}

src/Form/CarouselType.php
<?php

namespace App\Form;

use App\Entity\Carousel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarouselType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('imageFile', FileType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Carousel::class,
        ]);
    }
}

src/Controller/CarouselController.php
<?php

namespace App\Controller;

use App\Entity\Carousel;
use App\Form\CarouselType;
use App\Repository\CarouselRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/carousel")
 */
class CarouselController extends AbstractController
{
    private $repository;

    private $manager;

    public function __construct(CarouselRepository $repository, ObjectManager $manager)
    {
        $this->manager = $manager;
        $this->repository = $repository;
    }

    /**
     * @Route("/", name="carousel_index", methods={"GET"})
     */
    public function index(): Response
    {
        $carousels = $this->repository->findAll();
        return $this->render('carousel/index.html.twig', [
            'carousels' => $carousels
        ]);
    }

    /**
     * @Route("/new", name="carousel_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $carousel = new Carousel();
        $form = $this->createForm(CarouselType::class, $carousel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->manager->persist($carousel);
            $this->manager->flush();

            return $this->redirectToRoute('carousel_index');
        }

        return $this->render('carousel/new.html.twig', [
            'carousel' => $carousel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="carousel_show", methods={"GET"})
     */
    public function show(Carousel $carousel): Response
    {
        return $this->render('carousel/show.html.twig', [
            'carousel' => $carousel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="carousel_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Carousel $carousel): Response
    {
        $form = $this->createForm(CarouselType::class, $carousel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->manager->flush();

            return $this->redirectToRoute('carousel_index');
        }

        return $this->render('carousel/edit.html.twig', [
            'carousel' => $carousel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="carousel_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Carousel $carousel): Response
    {
        if ($this->isCsrfTokenValid('delete' . $carousel->getId(), $request->get('_token'))) {
            $this->manager->remove($carousel);
            $this->manager->flush();
        }

        return $this->redirectToRoute('carousel_index');
    }
}

templates/carousel/_delete_form.html.twig
<form method="post" action="{{ path('carousel_delete', {'id': carousel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ carousel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/carousel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/carousel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Carousel{% endblock %}

{% block body %}
    <h1>Edit Carousel</h1>

    {{ include('carousel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('carousel_index') }}">back to list</a>

    {{ include('carousel/_delete_form.html.twig') }}
{% endblock %}

templates/carousel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Carousel index{% endblock %}

{% block body %}
    <h1>Carousel index</h1>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      {% if carousel.image_name is defined %}
      <img src="{{ asset('images/carousels/') ~ carousel.image_name }}" class="d-block w-100" alt="slide 1" style="width: 1000px; height:500;">
      {% else %}
        <p>Pas d'image à uploader</p>
      {% endif %}
      
    </div>
    <div class="carousel-item">
      <img src="/images/bg_2.jpg" class="d-block w-100" alt="slide 2" style="width: 1000px; height:500;">
    </div>
    <div class="carousel-item">
      <img src="/images/bg_1.jpg" class="d-block w-100" alt="slide 3" style="width: 1000px; height:500;">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>ImageName</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for carousel in carousels %}
            <tr>
                <td>{{ carousel.id }}</td>
                <td>{{ carousel.imageName }}</td>
                <td>{{ carousel.updatedAt ? carousel.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('carousel_show', {'id': carousel.id}) }}">show</a>
                    <a href="{{ path('carousel_edit', {'id': carousel.id}) }}">edit</a>
                    <form method="post" action="{{ path('carousel_delete', {'id': carousel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ carousel.id) }}">
                        <button class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('carousel_new') }}">Create new</a>
{% endblock %}

templates/carousel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Carousel{% endblock %}

{% block body %}
    <h1>Create new Carousel</h1>

    {{ include('carousel/_form.html.twig') }}

    <a href="{{ path('carousel_index') }}">back to list</a>
{% endblock %}

templates/carousel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Carousel{% endblock %}

{% block body %}
    <h1>Carousel</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ carousel.id }}</td>
            </tr>
            <tr>
                <th>ImageName</th>
                <td>{{ carousel.imageName }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ carousel.updatedAt ? carousel.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('carousel_index') }}">back to list</a>

    <a href="{{ path('carousel_edit', {'id': carousel.id}) }}">edit</a>

    {{ include('carousel/_delete_form.html.twig') }}
{% endblock %}