src/Entity/Image.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ImageRepository")
 * @Vich\Uploadable
 */
class Image
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * 
     */
    private $id;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="imageName")
     */
    private $imageFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdone_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedone_at;

    public function __construct()
    {
        $this->createdone_at = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Get the value of imageFile
     *
     * @return  File|null
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @param  File|null  $imageFile
     *
     * @return  self
     */ 
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
         if ($this->imageFile instanceof UploadedFile) {
            $this->updatedone_at = new DateTime('now');
        }

        return $this;
    }

    /**
     * Get the value of imageName
     *
     * @return  string|null
     */ 
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * Set the value of imageName
     *
     * @param  string|null  $imageName
     *
     * @return  self
     */ 
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getCreatedoneAt(): ?\DateTimeInterface
    {
        return $this->createdone_at;
    }

    public function setCreatedoneAt(\DateTimeInterface $createdone_at): self
    {
        $this->createdone_at = $createdone_at;

        return $this;
    }

    public function getUpdatedoneAt(): ?\DateTimeInterface
    {
        return $this->updatedone_at;
    }

    public function setUpdatedoneAt(?\DateTimeInterface $updatedone_at): self
    {
        $this->updatedone_at = $updatedone_at;

        return $this;
    }
}

src/Form/ImageType.php
<?php

namespace App\Form;

use App\Entity\Image;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('imageName')
            ->add('createdone_at')
            ->add('updatedone_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Image::class,
        ]);
    }
}

src/Controller/ImageController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Form\Image1Type;
use App\Repository\ImageRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/image")
 */
class ImageController extends AbstractController
{
    /**
     * @var ObjectManager
     */
    private $manager;

    /**
     * @var ImageRepository
     */
    private $repository;
    public function __construct(ObjectManager $manager, ImageRepository $repository)
    {
        $this->manager = $manager;
        $this->repository = $repository;
    }
    /**
     * @Route("/", name="image_index", methods={"GET"})
     */
    public function index(): Response
    {
        $image = $this->repository->findAll();
        return $this->render('image/index.html.twig', [
            'images' => $image,
        ]);
    }

    /**
     * slide
     *
     * @return Response
     * @Route("/image/slide", name="image.slide")
     */
    public function slide(): Response
    {
        $image = $this->repository->findAll();
        return $this->render('image/slide.html.twig', [
            'images' => $image
        ]);
    }

    /**
     * @Route("/new", name="image_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $image = new Image();
        $form = $this->createForm(Image1Type::class, $image);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->manager->persist($image);
            $this->manager->flush();

            return $this->redirectToRoute('image_index');
        }

        return $this->render('image/new.html.twig', [
            'image' => $image,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="image_show", methods={"GET"})
     */
    public function show(Image $image): Response
    {
        return $this->render('image/show.html.twig', [
            'image' => $image,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="image_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Image $image): Response
    {
        $form = $this->createForm(Image1Type::class, $image);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->manager->flush();

            return $this->redirectToRoute('image_index');
        }

        return $this->render('image/edit.html.twig', [
            'image' => $image,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="image_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Image $image): Response
    {
        if ($this->isCsrfTokenValid('delete'.$image->getId(), $request->request->get('_token'))) {
            $this->manager->remove($image);
            $this->manager->flush();
        }

        return $this->redirectToRoute('image_index');
    }
}

templates/image/_delete_form.html.twig
<form method="post" action="{{ path('image_delete', {'id': image.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ image.id) }}">
    <button class="btn">Delete</button>
</form>

templates/image/_form.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col-2">
            {{ form_row(form.imageFile) }}
        </div>
    </div>
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/image/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Image{% endblock %}

{% block body %}
    <h1>Edit Image</h1>

    {{ include('image/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('image_index') }}">back to list</a>

    {{ include('image/_delete_form.html.twig') }}
{% endblock %}

templates/image/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Image index{% endblock %}

{% block body %}
    <h1>Image index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>ImageName</th>
                <th>Createdone_at</th>
                <th>Updatedone_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for image in images %}
            <tr>
                <td>{{ image.id }}</td>
                <td>{{ image.imageName }}</td>
                <td>{{ image.createdoneAt ? image.createdoneAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ image.updatedoneAt ? image.updatedoneAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('image_show', {'id': image.id}) }}">show</a>
                    <a href="{{ path('image_edit', {'id': image.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('image_new') }}" class="btn btn-info float-left rounded-pill">Create new</a>
    <a href="{{ path('image.slide') }}" class="btn btn-info float-right">Voir le carousel</a>
{% endblock %}

templates/image/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Image{% endblock %}

{% block body %}
    <h1>Create new Image</h1>

    {{ include('image/_form.html.twig') }}

    <a href="{{ path('image_index') }}">back to list</a>
{% endblock %}

templates/image/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Image{% endblock %}

{% block body %}
    <h1>Image</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ image.id }}</td>
            </tr>
            <tr>
                <th>ImageName</th>
                <td>{{ image.imageName }}</td>
            </tr>
            <tr>
                <th>Createdone_at</th>
                <td>{{ image.createdoneAt ? image.createdoneAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updatedone_at</th>
                <td>{{ image.updatedoneAt ? image.updatedoneAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('image_index') }}">back to list</a>

    <a href="{{ path('image_edit', {'id': image.id}) }}">edit</a>

    {{ include('image/_delete_form.html.twig') }}
{% endblock %}

templates/image/slide.html.twig
{% extends 'base.html.twig' %}


{% block body %}

<div class="row">
    <div class="col-md-offset-2  col-md-8 fondblanc2">
        <h1 class="lienstitre">Galerie photos</h1>
        {% for image in images %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 btn btn-default bloc-categorie" data-toggle="modal" data-target="{{ '#' ~ image.id }}">
        </div>
        <div id="{{ image.id }}" class="modal" role="dialog">
            <div class="modal-dialog modal-lg">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h2>Image N° {{ image.id }}</h2>

                    </div>
                    <div class="modal-body">

                        <div class="c-wrapper">
                            <div id="myCarousel" class="carousel slide" data-ride="carousel">

                                <ol class="carousel-indicators">
                                    {%  set isFirst = true %}
                                    {% for image in images %}
                                        {% if isFirst == true %}
                                            <li data-target="#myCarousel" data-slide-to="{{ loop.index0 }}" class="active"></li>
                                        {% else %}
                                            <li data-target="#myCarousel" data-slide-to="{{ loop.index0 }}"></li>
                                        {% endif %}

                                        {% set isFirst = false %}
                                    {% endfor %}
                                </ol>
                                <div class="carousel-inner" role="listbox">
                                    {%  set isFirst = true %}
                                        {% for image in images %}
                                            {% if isFirst == true %}
                                                <div class="item active">
                                            {% else %}
                                                <div class="item">
                                            {% endif %}
                                                {% if image.imageName %}
                                                    <img src="/images/products/{{ image.imageName }}" alt="">
                                                {% endif %}
                                                </div>
                                        {% set isFirst = false %}
                                        {% endfor %}
                                    </div>
                                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
            
        </div>
    </div>


    {% endblock %}